name: parish_aid_admin
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: '>=3.1.5 <4.0.0'


dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2
  get: ^4.6.6
  flutter_bloc: ^8.1.4
  font_awesome_flutter: ^10.6.0
  http: ^1.1.0
  flutter_screenutil: ^5.9.0
  gap: ^2.0.0
  intl: ^0.19.0
  shared_preferences: ^2.2.2
  flutter_inappwebview: ^6.0.0
  fpdart: ^1.1.0
  equatable: ^2.0.5
  fluttertoast: ^8.2.2
  get_it: ^7.6.7
  internet_connection_checker: ^1.0.0+1
  top_snackbar_flutter: ^3.1.0
  google_fonts: ^6.2.1
  flutter_spinkit: ^5.2.1
  cached_network_image: ^3.3.1
  camera: ^0.10.5+9
  dropdown_search: ^5.0.6
  email_validator: ^2.1.17
  image: ^4.1.7
  image_cropper: ^5.0.1
  image_picker: ^1.0.8
  shimmer: ^3.0.0
  flutter_svg: ^2.0.10+1
  animated_splash_screen: ^1.3.0
  dropdown_button2: ^2.3.9
  nigerian_states_and_lga: ^1.0.0
  form_validator: ^2.1.1
  segmented_progress_bar: ^1.1.0
  logger: ^2.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^2.0.0


flutter:


  uses-material-design: true

  assets:
     - assets/
     - assets/images/
